defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dir: "/cluster/nvme4a/whh/dataset/geo-fno"
  dataset_name: "airfoil-flow" 
  data_to_encode:
  ntrain : 
  ntest : 
  sub_tr : 1
  sub_from : 1
  sub_te : 1
  seed: 123
  same_grid: True
  sequence_length: 20

optim:
  batch_size: 32
  batch_size_val: 
  lr_inr : 5e-6
  gamma_step : 0.9
  lr_code : 0.01
  meta_lr_code : 5e-6
  weight_decay_code: 0
  inner_steps : 3
  test_inner_steps : 3
  epochs : 1000
  lr_mlp : 1e-3
  weight_decay_mlp: 0
  lr_grid : 0.01
  optim_out: True
  optim_in: True 
  share_latent_sync: False
  decode_in_prob: 0.5

inr_in:
  model_type : "siren"
  latent_dim : 128
  depth : 4
  hidden_dim : 256
  w0 : 10
  use_latent: True
  modulate_scale: False
  modulate_shift: True
  hypernet_depth: 1
  hypernet_width: 128
  last_activation: 
  loss_type: "mse"
  use_norm: True 
  grid_size: 64
  grid_size_2: 0
  siren_init: True
  grid_base: 64
  grid_sum: True
  share_grid: False
  run_name:

inr_out:
  model_type : "siren"
  latent_dim : 128
  depth : 4
  hidden_dim : 256
  w0 : 30
  use_latent: True
  modulate_scale: False
  modulate_shift: True
  hypernet_depth: 1
  hypernet_width: 128
  last_activation: 
  loss_type: "mse"
  use_norm: True 
  grid_size: 64
  grid_size_2: 0
  siren_init: True
  grid_base: 64
  grid_sum: True
  share_grid: False

model:
  model_type: resnet
  depth: 3
  width: 64
  dropout: 0
  activation: swish
  lr: 1e-3
# airfoil
inr:
  inner_steps: 3
  run_name: 
  run_dict:
    pressure: denim-frost-3448
    density: fluent-planet-3586
    vx: gallant-jazz-3402
    vy: fresh-wave-3583

wandb:
  entity: "wanghonghui1998"
  project: "marble"
  name: 
  id: 
  dir: 
  sweep_id: 
  saved_checkpoint: False
  checkpoint_path:

distributed: False
world_size: 1
gpu_id: 0
rank: 0 
ddp:
  port : 29051
  launcher: 
  
jz: 
  program: training/inr.py
  mode: dev
  partition: gpu_p2