defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dir: "/cluster/nvme4a/whh/dataset/geo-fno"
  dataset_name: "airfoil" 
  data_to_encode:
  ntrain : 
  ntest : 
  sub_tr : 1
  sub_from : 1
  sub_te : 1
  seed: 123
  same_grid: True
  sequence_length: 20

optim:
  batch_size: 64
  batch_size_val: 
  lr : 1e-3
  weight_decay: 0
  gamma_step : 0.9
  epochs : 1000
  mixup_w: 1.0 
  mixup_alpha: 0.5

model:
  model_type: resnet
  depth: 3
  width: 64
  dropout: 0
  activation: swish

# airfoil
inr:
  inner_steps: 3
  run_name:
  run_name_in:

wandb:
  entity: "wanghonghui1998"
  project: "marble"
  name: 
  id: 
  dir: 
  sweep_id: 
  saved_checkpoint: False
  checkpoint_path:
  evaluate:


jz: 
  program: training/inr.py
  mode: dev
  partition: gpu_p2