defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dir: "/data/serrano/"
  dataset_name: "shallow-water-dino" 
  data_to_encode:
  ntrain : 
  ntest : 
  sub_from : 2
  sub_tr : 0.0125
  sub_te : 0.0125
  seed: 123
  same_grid: True
  seq_inter_len : 20
  seq_extra_len : 20
  n_cond: 0 
optim:
  batch_size: 64
  batch_size_val: 
  lr : 0.001
  weight_decay: 0
  gamma_step : 0.9
  epochs : 1000
  n_steps: 1000
  lr_adapt: 0.01

dynamics:
  model_type: ode
  depth: 3
  width: 512
  modes: 12
  teacher_forcing_init: 0.99
  teacher_forcing_decay: 0.99
  teacher_forcing_update: 10
  normalize_per_ele: True
  run_name : prime-darkness-4874 # sandy-pyramid-4897 #prime-darkness-4874 #iconic-firefly-4657 #atomic-surf-4656
  
inr:
  inner_steps: 3
  run_name: 
  run_dict:
  run_name_suffix: ""
  grid_channel: 6
  grid_size: 64

wandb:
  entity: "wanghonghui1998"
  project: "functa2functa"
  name: 
  id: 
  dir: 
  sweep_id: 
  saved_checkpoint: False
  checkpoint_path:
  evaluate:


jz: 
  program: training/inr.py
  mode: dev
  partition: gpu_p2