defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dir: "/data/serrano/"
  dataset_name: "shallow-water-dino" 
  data_to_encode:
  ntrain : 
  ntest : 
  sub_from :
  sub_tr : 2
  sub_te : 2
  seed: 123
  same_grid: True
  seq_inter_len : 20 
  seq_extra_len : 20

optim:
  batch_size: 32
  batch_size_val: 
  lr_inr : 0.000005
  gamma_step : 0.9
  lr_code : 0.01
  lr_edg : 0.01
  meta_lr_code : 0.000005
  weight_decay_code: 0
  inner_steps : 3
  test_inner_steps : 3
  n_steps : 1000
  epochs : 10000
  update_modulations: False
  random_init: False 
  update_alpha: True 
  lr_adapt: 0.01
  use_cl: False
  use_cls: False
  temperature: 1.0
  w_cl: 1.0 
  lr_grid : 0.01

inr:
  model_type : "siren"
  latent_dim : 256
  depth : 6
  hidden_dim : 256
  w0 : 30
  use_latent: True
  modulate_scale: False
  modulate_shift: True
  hypernet_depth: 1
  hypernet_width: 128
  last_activation: 
  loss_type: "mse"
  use_norm: True 
  grid_size: 64
  siren_init: True
  n_levels: 4
  n_features_per_level: 2
  log2_hashmap_size: 12
  base_resolution: 4
  per_level_scale: 2
  base_sigma: 5.0
  exp_sigma: 2.0
  num_init: 1
  scale_init: 1e-3
  grid_base: 64
  grid_sum: True
  share_grid: False
  share_code: True
  k_mixture: 256
  grid_init_channel: 32
  grid_scale_ratio: 1.0
  
wandb:
  entity: "wanghonghui1998"
  project: "functa2functa"
  name: 
  id: 
  dir:
  sweep_id:
  saved_checkpoint : False
  checkpoint_path :

jz: 
  program: training/inr.py
  mode: dev
  partition: gpu_p2

distributed: False
world_size: 1
gpu_id: 0
rank: 0 
ddp:
  port : 29051
  launcher: 